apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
    tier: database
spec:
  containers:
  - name: backend
    image: postgres:13
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "testdb"
    - name: POSTGRES_USER
      value: "testuser"
    - name: POSTGRES_PASSWORD
      value: "testpass"
